### ISSUE TITLE
Object { error: "popup_closed_by_user" } in FireFox in some cases. Chrome works fine.

### ISSUE THREAD

**Issue by function1983** [mejiamanuel57/vue-google-signin-button-directive#1]
Hi, thank you for your plugin. Here is my situation since your plugin doesn't seem to run really consistently.

Browser | My App | Your app
--- | --- | ---
Firefox|  __error: "popup_closed_by_user"__ | OK
Firefox (private mode) | OK | OK
Chrome | OK | OK

What do you think the issue is?

**Comment by function1983** [comment]
I found out that firefox block facebook by default due to it's tracking protection feature. Could you put it somewhere in the README.md for others?
https://stackoverflow.com/questions/33855626/firefox-blocking-facebook-js

**Comment by mejiamanuel57** [comment]
Hi @fuction1983, I will add it to the README.md and thanks. Also, this repo is open for collaboration if you have any feature that you would like to include.
